# Generated by Django 3.1.7 on 2021-03-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('parse_number', models.IntegerField(default=1)),
            ],
        ),
    ]
