# Generated by Django 3.1.7 on 2021-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoresult',
            name='engine',
            field=models.TextField(default='ert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoresult',
            name='keywords',
            field=models.TextField(default='trssff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoresult',
            name='location',
            field=models.TextField(default='nghn'),
            preserve_default=False,
        ),
    ]
